### ISSUE TITLE
Fix homebrew release

### ISSUE THREAD

**Issue by sgaunet** [sgaunet/gocrypt#6]
Add/fix documentation:

```
brew tap sgaunet/homebrew-tools
brew install sgaunet/tools/gocrypt
```

Fix goreleaser configuration:

```
brews:
  - homepage: 'https://github.com/sgaunet/homebrew-tools'
    directory: Formula
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
```
